/** Images et logos utilisés sur la page d'accueil (hero → CTA). */
export const HOME_PRELOAD_ASSETS = [
  '/background-hero.png',
  '/rock-2.png',
  '/about-thumb.png',
  '/about5.png',
  '/feature-design-1.png',
  '/feature-design-2.png',
  '/service1.png',
  '/service2.png',
  '/service3.png',
  '/service4.png',
  '/service5.png',
  '/service6.png',
  '/project1.png',
  '/project2.png',
  '/project3.png',
  '/project4.png',
  '/project5.png',
  '/project-area-bg.png',
  '/testi-bg.png',
  '/testi1.png',
  '/logo-rock-digital-blanc-v1.svg',
  '/logo-rock-digital-color-v1.svg',
] as const;
